version: '3'

services:
  postgres:
    container_name: olist_db
    image: postgres:13
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: postgresql
    ports:
      - 5432:5432
    # volumes:
      # - './.postgres:/var/lib/postgresql/data/'
      # - ./sql/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      # - ./init-scripts:/docker-entrypoint-initdb.d
      # - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5